FollowPath:
  plugin: "mpc_controller::MpcControllerNode"
  mpc:
    qx: 
    qy: 
    qtheta:
    rvx:
    rvy:
    romega:
    qx_e:
    qy_e:
    qtheta_e:
  nav:
    use_interpolation: true
    use_curvature_scaling: true
    curvature_min: 0.1
    curvature_max: 0.5
    reduction_ratio_at_high_curvature: 0.5
    curvature_forward_dist: 1.0
    curvature_backward_dist: 1.0
    max_velocity_scaling_factor_rate: 0.1
