FollowPath:
  plugin: "mpc_controller::MpcControllerNode"
  mpc:
    qx: 30.0
    qy: 30.0
    qtheta: 15.0
    rvx: 1.0
    rvy: 1.0
    romega: 0.5
    qx_e: 10.0
    qy_e: 10.0
    qtheta_e: 5.0
  nav:
    use_interpolation: false
    use_curvature_scaling: false
    curvature_min: 0.1
    curvature_max: 0.5
    reduction_ratio_at_high_curvature: 0.5
    curvature_forward_dist: 1.0
    curvature_backward_dist: 1.0
    max_velocity_scaling_factor_rate: 0.1
